
export const OG_LEVELS: { [key: number]: { name: string; info?: string }[] } = {
    1: [
      { name: "assessment" }, { name: "syllables" }, { name: "consonant" }, { name: "vowel" }, { name: "closed syllables" }, { name: "a" }, { name: "e" }, { name: "i" }, { name: "o" }, { name: "u" }, 
      { name: "y" }, { name: "z" }, { name: "x" }, { name: "c" }, { name: "v" }, { name: "b" }, { name: "n" }, { name: "m" }, { name: "l" }, { name: "k" }, { name: "j" }, { name: "h" }, { name: "g" }, { name: "f" }, { name: "d" }, { name: "s" }, { name: "q" }, { name: "u" }, { name: "w" }, 
      { name: "r" }, { name: "t" }, { name: "p" }, { name: "ss" }, { name: "ll" }, { name: "zz" }, { name: "ff" }, { name: "ch" }, { name: "sh" }, { name: "th" }, { name: "wh" }, { name: "tch" }, { name: "bl" }, { name: "st" }, { name: "str" }, { name: "sp" }, 
      { name: "spr" }, { name: "fl" }, { name: "cl" }, { name: "i-e" }, { name: "a-e" }, { name: "an" }, { name: "beginning blends" }, { name: "o-e" }, { name: "e-e" }, { name: "u-e" }
    ],
    2: [
      { name: "open syllable" }, { name: "y says i" }, 
      { 
        name: "y says e",
        info: "Concept: Suffix -y.\nWhen it is used: Added to the end of a noun to turn it into an adjective.\nMeaning: \"Characterized by,\" \"full of,\" or \"like.\" (e.g., dusty means full of dust).\nSuffix -y vs. Candy (The /ē/ sound):\nThe Suffix -y: This is a functional unit. If you remove the \"y,\" you are left with a recognizable base word (e.g., sand + y = sandy). It changes the part of speech from a noun to an adjective.\nThe \"y says e\" in Candy: In words like candy, puppy, or pony, the \"y\" is simply the spelling for the /ē/ sound at the end of a multi-syllabic word. If you remove the \"y,\" the remaining part is not usually a standalone word (e.g., \"cand\" is not a word).\nCommon Student Confusions: Students may confuse these because they sound the same. Teach them to look for the \"base word\" to determine if it is a suffix or just a spelling pattern.\n\nHistory of the Concept\nThe suffix -y is of Anglo-Saxon (Old English) origin. In Old English, it was originally spelled -ig. Over centuries, the /g/ sound was dropped in speech, leaving only the vowel sound. By the Middle English period, the spelling shifted to -y or -ie. This suffix is one of the most productive in the English language, allowing us to turn almost any noun into a descriptive word. It is a hallmark of Germanic English, used for simple, everyday descriptions of textures, weather, and feelings."
      }, 
      { name: "y generalization" }, { name: "tch" }, { name: "ch/tch generalization" }, 
      { name: "ang" }, { name: "ing" }, { name: "ung" }, { name: "ink" }, { name: "ank" }, { name: "unk" }, { name: "ar" }, { name: "ir" }, { name: "ur" }, { name: "er" }, { name: "or" }, { name: "-s" }, { name: "ve" }, { name: "-er" }, { name: "war" }, 
      { name: "wor" }, { name: "ct" }, { name: "ic" }, { name: "vc/cv" }, { name: "vc/ccv" }, { name: "vcc/cv" }, { name: "ai" }, { name: "ay" }, { name: "ai/ay generalizations" }, 
      { name: "v-e/c" }, { name: "verb s" }, 
      { 
        name: "se",
        info: "This spelling pattern is a legacy of the Norman Conquest and the work of French scribes. In Old English, words like house (hus) ended in a single s. However, as English spelling became standardized, scribes wanted to distinguish between words that were plural and words that just happened to end in the /s/ sound. They adopted the French habit of adding a silent e to \"protect\" the s from looking like a suffix. This helped readers immediately identify that the word was a single, whole unit rather than a plural noun."
      }, 
      { 
        name: "-ed (t)",
        info: "Concept: The suffix -ed.\nWhen it is used: To indicate that an action happened in the past.\nOG Generalizations:\nThe /id/ sound: If the base word ends in the sound /t/ or /d/, the suffix -ed is pronounced /id/ (e.g., plant-ed). This is the only version that adds a new syllable to the word.\nThe /t/ sound: If the base word ends in an unvoiced sound (p, k, f, s, sh, ch, th), the suffix -ed is pronounced /t/ (e.g., jump-ed).\nThe /d/ sound: If the base word ends in a voiced sound (all vowels, b, g, l, m, n, r, v, z), the suffix -ed is pronounced /d/ (e.g., fill-ed).\nCommon Student Confusions: Students often try to spell words phonetically (e.g., jumpt or filld). Remind them that if the word is an action that already happened, they must use the unit -ed.\n\nHistory of the Concept\nThe suffix -ed is deeply rooted in Old English (Anglo-Saxon). Historically, there were several different endings to mark the past tense (-ode, -ede, -de). During the Middle English period, these endings began to merge and standardize into the single suffix -ed. While the spelling became fixed, the pronunciation continued to adapt to the sounds surrounding it to make words easier to say (a process called assimilation). English kept the single spelling -ed to help the reader recognize the \"past tense\" meaning immediately, regardless of how it is whispered or spoken."
      }, 
      { 
        name: "-ed (d)",
        info: "Concept: The suffix -ed.\nWhen it is used: To indicate that an action happened in the past.\nOG Generalizations:\nThe /id/ sound: If the base word ends in the sound /t/ or /d/, the suffix -ed is pronounced /id/ (e.g., plant-ed). This is the only version that adds a new syllable to the word.\nThe /t/ sound: If the base word ends in an unvoiced sound (p, k, f, s, sh, ch, th), the suffix -ed is pronounced /t/ (e.g., jump-ed).\nThe /d/ sound: If the base word ends in a voiced sound (all vowels, b, g, l, m, n, r, v, z), the suffix -ed is pronounced /d/ (e.g., fill-ed).\nCommon Student Confusions: Students often try to spell words phonetically (e.g., jumpt or filld). Remind them that if the word is an action that already happened, they must use the unit -ed.\n\nHistory of the Concept\nThe suffix -ed is deeply rooted in Old English (Anglo-Saxon). Historically, there were several different endings to mark the past tense (-ode, -ede, -de). During the Middle English period, these endings began to merge and standardize into the single suffix -ed. While the spelling became fixed, the pronunciation continued to adapt to the sounds surrounding it to make words easier to say (a process called assimilation). English kept the single spelling -ed to help the reader recognize the \"past tense\" meaning immediately, regardless of how it is whispered or spoken."
      }, 
      { 
        name: "-ed (id)",
        info: "Concept: The suffix -ed.\nWhen it is used: To indicate that an action happened in the past.\nOG Generalizations:\nThe /id/ sound: If the base word ends in the sound /t/ or /d/, the suffix -ed is pronounced /id/ (e.g., plant-ed). This is the only version that adds a new syllable to the word.\nThe /t/ sound: If the base word ends in an unvoiced sound (p, k, f, s, sh, ch, th), the suffix -ed is pronounced /t/ (e.g., jump-ed).\nThe /d/ sound: If the base word ends in a voiced sound (all vowels, b, g, l, m, n, r, v, z), the suffix -ed is pronounced /d/ (e.g., fill-ed).\nCommon Student Confusions: Students often try to spell words phonetically (e.g., jumpt or filld). Remind them that if the word is an action that already happened, they must use the unit -ed.\n\nHistory of the Concept\nThe suffix -ed is deeply rooted in Old English (Anglo-Saxon). Historically, there were several different endings to mark the past tense (-ode, -ede, -de). During the Middle English period, these endings began to merge and standardize into the single suffix -ed. While the spelling became fixed, the pronunciation continued to adapt to the sounds surrounding it to make words easier to say (a process called assimilation). English kept the single spelling -ed to help the reader recognize the \"past tense\" meaning immediately, regardless of how it is whispered or spoken."
      }, 
      { 
        name: "-y",
        info: "Concept: Suffix -y.\nWhen it is used: Added to the end of a noun to turn it into an adjective.\nMeaning: \"Characterized by,\" \"full of,\" or \"like.\" (e.g., dusty means full of dust).\nSuffix -y vs. Candy (The /ē/ sound):\nThe Suffix -y: This is a functional unit. If you remove the \"y,\" you are left with a recognizable base word (e.g., sand + y = sandy). It changes the part of speech from a noun to an adjective.\nThe \"y says e\" in Candy: In words like candy, puppy, or pony, the \"y\" is simply the spelling for the /ē/ sound at the end of a multi-syllabic word. If you remove the \"y,\" the remaining part is not usually a standalone word (e.g., \"cand\" is not a word).\nCommon Student Confusions: Students may confuse these because they sound the same. Teach them to look for the \"base word\" to determine if it is a suffix or just a spelling pattern.\n\nHistory of the Concept\nThe suffix -y is of Anglo-Saxon (Old English) origin. In Old English, it was originally spelled -ig. Over centuries, the /g/ sound was dropped in speech, leaving only the vowel sound. By the Middle English period, the spelling shifted to -y or -ie. This suffix is one of the most productive in the English language, allowing us to turn almost any noun into a descriptive word. It is a hallmark of Germanic English, used for simple, everyday descriptions of textures, weather, and feelings."
      }, 
      { name: "ee" }, { name: "ea" }, { name: "ey" }, { name: "all" }, { name: "al" }, 
      { 
        name: "ind",
        info: "What it is: These patterns (-olt, -ost, -ild, -ind, -old) are known as \"Closed Syllable Exceptions\" or \"Wild Old Words.\"\nGeneralization: Usually, a vowel in a closed syllable (ending in one or more consonants) is short. However, in these specific clusters, the vowel \"breaks the rule\" and says its name (long sound).\nMnemonic: Many teachers use the phrase \"Wild Old Kind Ghost\" to help students remember that i and o can be long when followed by these specific consonant pairs.\nCommon Student Confusions: Students may try to use a silent e to make the vowel long (e.g., spelling find as finde). Remind them that these clusters are \"strong\" enough to make the vowel long on their own.\n\nHistory of the Concept\nThese words are almost exclusively of Anglo-Saxon (Old English) origin. In Old English, these vowels were actually short. However, during a period called \"Homorganic Lengthening\" (around the 9th century), short vowels began to stretch out and become long when they appeared before certain consonant clusters—specifically clusters made of a \"liquid\" or \"nasal\" sound plus another consonant (like ld or nd).\nWhile most closed syllables stayed short, these specific combinations were so common in spoken Old English that the long vowel sound became the standard. English kept this pattern even after the Great Vowel Shift, which is why words like child (long i) and children (short i) have different vowel sounds today—the cluster was \"broken\" in the plural form, so the vowel stayed short!"
      }, 
      { 
        name: "ild",
        info: "What it is: These patterns (-olt, -ost, -ild, -ind, -old) are known as \"Closed Syllable Exceptions\" or \"Wild Old Words.\"\nGeneralization: Usually, a vowel in a closed syllable (ending in one or more consonants) is short. However, in these specific clusters, the vowel \"breaks the rule\" and says its name (long sound).\nMnemonic: Many teachers use the phrase \"Wild Old Kind Ghost\" to help students remember that i and o can be long when followed by these specific consonant pairs.\nCommon Student Confusions: Students may try to use a silent e to make the vowel long (e.g., spelling find as finde). Remind them that these clusters are \"strong\" enough to make the vowel long on their own.\n\nHistory of the Concept\nThese words are almost exclusively of Anglo-Saxon (Old English) origin. In Old English, these vowels were actually short. However, during a period called \"Homorganic Lengthening\" (around the 9th century), short vowels began to stretch out and become long when they appeared before certain consonant clusters—specifically clusters made of a \"liquid\" or \"nasal\" sound plus another consonant (like ld or nd).\nWhile most closed syllables stayed short, these specific combinations were so common in spoken Old English that the long vowel sound became the standard. English kept this pattern even after the Great Vowel Shift, which is why words like child (long i) and children (short i) have different vowel sounds today—the cluster was \"broken\" in the plural form, so the vowel stayed short!"
      }, 
      { 
        name: "old",
        info: "What it is: These patterns (-olt, -ost, -ild, -ind, -old) are known as \"Closed Syllable Exceptions\" or \"Wild Old Words.\"\nGeneralization: Usually, a vowel in a closed syllable (ending in one or more consonants) is short. However, in these specific clusters, the vowel \"breaks the rule\" and says its name (long sound).\nMnemonic: Many teachers use the phrase \"Wild Old Kind Ghost\" to help students remember that i and o can be long when followed by these specific consonant pairs.\nCommon Student Confusions: Students may try to use a silent e to make the vowel long (e.g., spelling find as finde). Remind them that these clusters are \"strong\" enough to make the vowel long on their own.\n\nHistory of the Concept\nThese words are almost exclusively of Anglo-Saxon (Old English) origin. In Old English, these vowels were actually short. However, during a period called \"Homorganic Lengthening\" (around the 9th century), short vowels began to stretch out and become long when they appeared before certain consonant clusters—specifically clusters made of a \"liquid\" or \"nasal\" sound plus another consonant (like ld or nd).\nWhile most closed syllables stayed short, these specific combinations were so common in spoken Old English that the long vowel sound became the standard. English kept this pattern even after the Great Vowel Shift, which is why words like child (long i) and children (short i) have different vowel sounds today—the cluster was \"broken\" in the plural form, so the vowel stayed short!"
      }, 
      { 
        name: "ost",
        info: "What it is: These patterns (-olt, -ost, -ild, -ind, -old) are known as \"Closed Syllable Exceptions\" or \"Wild Old Words.\"\nGeneralization: Usually, a vowel in a closed syllable (ending in one or more consonants) is short. However, in these specific clusters, the vowel \"breaks the rule\" and says its name (long sound).\nMnemonic: Many teachers use the phrase \"Wild Old Kind Ghost\" to help students remember that i and o can be long when followed by these specific consonant pairs.\nCommon Student Confusions: Students may try to use a silent e to make the vowel long (e.g., spelling find as finde). Remind them that these clusters are \"strong\" enough to make the vowel long on their own.\n\nHistory of the Concept\nThese words are almost exclusively of Anglo-Saxon (Old English) origin. In Old English, these vowels were actually short. However, during a period called \"Homorganic Lengthening\" (around the 9th century), short vowels began to stretch out and become long when they appeared before certain consonant clusters—specifically clusters made of a \"liquid\" or \"nasal\" sound plus another consonant (like ld or nd).\nWhile most closed syllables stayed short, these specific combinations were so common in spoken Old English that the long vowel sound became the standard. English kept this pattern even after the Great Vowel Shift, which is why words like child (long i) and children (short i) have different vowel sounds today—the cluster was \"broken\" in the plural form, so the vowel stayed short!"
      }, 
      { 
        name: "olt",
        info: "What it is: These patterns (-olt, -ost, -ild, -ind, -old) are known as \"Closed Syllable Exceptions\" or \"Wild Old Words.\"\nGeneralization: Usually, a vowel in a closed syllable (ending in one or more consonants) is short. However, in these specific clusters, the vowel \"breaks the rule\" and says its name (long sound).\nMnemonic: Many teachers use the phrase \"Wild Old Kind Ghost\" to help students remember that i and o can be long when followed by these specific consonant pairs.\nCommon Student Confusions: Students may try to use a silent e to make the vowel long (e.g., spelling find as finde). Remind them that these clusters are \"strong\" enough to make the vowel long on their own.\n\nHistory of the Concept\nThese words are almost exclusively of Anglo-Saxon (Old English) origin. In Old English, these vowels were actually short. However, during a period called \"Homorganic Lengthening\" (around the 9th century), short vowels began to stretch out and become long when they appeared before certain consonant clusters—specifically clusters made of a \"liquid\" or \"nasal\" sound plus another consonant (like ld or nd).\nWhile most closed syllables stayed short, these specific combinations were so common in spoken Old English that the long vowel sound became the standard. English kept this pattern even after the Great Vowel Shift, which is why words like child (long i) and children (short i) have different vowel sounds today—the cluster was \"broken\" in the plural form, so the vowel stayed short!"
      }, 
      { name: "-ing" }, { name: "oa" }, { name: "oe" }, { name: "ow" }, { name: "oo food" }, { name: "oo book" }, { name: "ou" }, 
      { name: "ou/ow generalization" }, { name: "assessment" }
    ],
    3: [
      { name: "contractions" }, { name: "possessives" }, { name: "oi" }, { name: "oy" }, { name: "oi/oy generalization" }, { name: "au" }, { name: "aw" }, { name: "au/aw generalization" }, 
      { name: "ou" }, { name: "ie" }, { name: "ea bread" }, { name: "ea steak" }, { name: "ie piece" }, { name: "igh" }, { name: "ph" }, { name: "vowel consonant 1" }, { name: "vowel consonant 2" }, 
      { name: "vowel consonant 3" }, { name: "-es" }, { name: "-ly" }, { name: "-est" }, { name: "ce" }, { name: "ci" }, { name: "cy" }, { name: "ge" }, { name: "gy" }, { name: "gi" }, { name: "-tion" }, { name: "-sion (shun)" }, 
      { name: "-sion (zhun)" }, { name: "-ment" }, { name: "-ful" }, { name: "-ness" }, { name: "-ish" }, { name: "-en" }, { name: "-less" }, { name: "schwa a" }, { name: "schwa i" }, { name: "doubling rule" }, 
      { name: "assessment" }
    ],
    4: [
      { name: "ple" }, { name: "ble" }, { name: "cle" }, { name: "dle" }, { name: "fle" }, { name: "gle" }, { name: "tle" }, { name: "kle" }, { name: "dge" }, { name: "dge and ge" }, { name: "stle" }, { name: "ckle" }, { name: "v.v" }, 
      { name: "ei /e/ ceiling" }, { name: "ew /u/ few" }, { name: "ew /oo/ grew" }, { name: "ui /oo/ juice" }, { name: "ei /a/ vein" }, { name: "ey /a/ they" }, 
      { name: "ue /u/ rescue" }, { name: "ue /oo/ true" }, { name: "eigh /a/ eight" }, { name: "y-e /i/ type" }, { name: "un-" }, { name: "re-" }, { name: "dis-" }, { name: "pro-" }, 
      { name: "cor-" }, { name: "con-" }, { name: "com-" }, { name: "con drops n" }, { name: "de-" }, { name: "pre-" }, { name: "sub-" }, { name: "trans-" }, { name: "non-" }, { name: "silent e rule" }, 
      { name: "y rule" }, { name: "doubling rule" }, { name: "struct" }, { name: "tract" }, { name: "port" }, { name: "ject" }, { name: "miss" }, { name: "mit" }, { name: "spire" }, { name: "scrib" }, 
      { name: "script" }, { name: "-sed-" }, { name: "-sit-" }, { name: "-sess-" }, { name: "act" }, { name: "dic" }, { name: "dict" }, { name: "fin" }, { name: "rupt" }, { name: "spect" }, { name: "spec" }, { name: "spic" }, 
      { name: "gram" }, { name: "graph" }, { name: "meter" }, { name: "metre" }, { name: "vers" }, { name: "vert" }, { name: "fer" }, { name: "cid/cis" }, { name: "form" }, { name: "Level 4 Assessment" }
    ],
    5: [
      { name: "rh" }, { name: "kn" }, { name: "gh" }, { name: "wr" }, { name: "gn" }, { name: "mb" }, { name: "gu" }, { name: "mn" }, { name: "ch /k/" }, { name: "ch /sh/" }, { name: "y /i/" }, { name: "o /u/ mother" }, 
      { name: "i /e/ studio" }, { name: "ive /iv/" }, { name: "u /u/ pull" }, { name: "ale" }, { name: "ton" }, { name: "om" }, { name: "que /k/" }, { name: "qu says /k/" }, { name: "gue /g/" }, 
      { name: "wa /wo/" }, { name: "qua /kwo/" }, { name: "ou /u/" }, { name: "augh /ot/" }, { name: "ough /ot/" }, { name: "ouar /er/" }, { name: "or /er/" }, { name: "oar /or/" }, 
      { name: "ear /er/" }, { name: "ear /ar/" }, { name: "quar /wor/" }, { name: "sc /s/" }, { name: "ti /sh/" }, { name: "ci /sh/" }, { name: "tu /choo/" }, { name: "age /aj/" }, 
      { name: "ain /en/" }, { name: "ture /cher/" }, { name: "ous /es/" }, { name: "cial /shel/" }, { name: "tial /shel/" }, { name: "ance /ence/" }, { name: "ence /ence/" }, 
      { name: "cal /kel/" }, { name: "cle /kel/" }, { name: "cian /shen/" }, { name: "able /ebl/" }, { name: "ible /ebl/" }, { name: "ate /it/" }, { name: "alt" }, { name: "en /en/" }, 
      { name: "alk /olk/" }, { name: "ty /te/" }, { name: "ive /ev/" }, { name: "el /ul/" }, { name: "age /ij/" }, { name: "ious" }, { name: "iate /e/at" }, { name: "ible" }, { name: "ial /e l/" }
    ]
};